development:
  adapter: postgresql
  encoding: unicode
  database: messages_development
  host: localhost
  pool: 5
  username: rails
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: messages_test
  host: localhost
  pool: 5
  username: rails
  password: password