development:
  adapter: postgresql
  encoding: unicode
  database: messages_development
  pool: 5
  username: rails
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: messages_test
  pool: 5
  username: rails
  password: password